
package Vista;

import Gestor.Conexion;
import Modelo.Articulo;
import Modelo.ArticuloDAO;
import Modelo.Compras;
import Modelo.ComprasDAO;
import Modelo.DetalleCompras;
import Modelo.MedioPago;
import Modelo.Proveedor;
import Modelo.ProveedorDAO;
import static Vista.Principal.VentanaPrincipal;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.sql.SQLException;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;


public class Compra extends javax.swing.JInternalFrame {

    Conexion enlace = new Conexion();
    Connection conect = enlace.conectar();
    
    Articulo a = new Articulo();
    Proveedor p = new Proveedor();
    Compras c = new Compras();
    DetalleCompras dc= new DetalleCompras();
    MedioPago mp = new MedioPago();
    
    ArticuloDAO adao= new ArticuloDAO();
    ComprasDAO cdao = new ComprasDAO();
    ProveedorDAO pdao = new ProveedorDAO();
    
    DefaultTableModel modelo = new DefaultTableModel();
    
    int idp;
    double tpagar;
    
    Calendar fecha_actual= new GregorianCalendar();
    
    public Compra() {
        initComponents();
        
        generarSerie();
        
        jdcFecha.setCalendar(fecha_actual);
        
        btnBuscarProducto.setEnabled(false);
        
        txtCodProveedor.requestFocus();
        txtCodProveedor.setBackground(Color.yellow);
        
        //txtMedioPago.setText(""+mp.getMedioPago());
        
        txtCantidad.setEnabled(false);
        txtCodProducto.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnGenerarCompra.setEnabled(false);
    }
    
    void generarSerie()
    {
        String serie=cdao.NroSerieCompra();
        int increment = 0;
        if(serie==null)
        {
            txtSerie.setText("000001");
        }
        else
        {
            increment=Integer.parseInt(serie);
            increment= increment +1;
            if(increment < 10)
            {
                txtSerie.setText("00000"+increment);
            }
            else
            {
                txtSerie.setText("0000"+increment);
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cboComprobante = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodProveedor = new javax.swing.JTextField();
        txtCodProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPago = new javax.swing.JTextField();
        txtProveedor = new javax.swing.JTextField();
        txtProducto = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        btnBuscarProducto = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBuscarPago = new javax.swing.JButton();
        txtMedioPago = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDetalle = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnGenerarCompra = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Compra");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("COMPRAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NUM. SERIE");

        txtSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("TIPO COMPROBANTE");

        cboComprobante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboComprobante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FACTURA", "TICKET", "TICKET FACTURA", "REMITO", "PRESUPUESTO" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("FECHA:");

        jdcFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("COD. PROVEEDOR");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("COD. PRODUCTO");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("PRECIO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CANTIDAD ADQUIRIDA");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("COD. MEDIO PAGO");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("PROVEEDOR");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("PRODUCTO");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("STOCK");

        txtCodProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodProveedorKeyPressed(evt);
            }
        });

        txtCodProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProductoActionPerformed(evt);
            }
        });
        txtCodProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodProductoKeyPressed(evt);
            }
        });

        txtPrecio.setEditable(false);
        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrecio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPrecioPropertyChange(evt);
            }
        });

        txtCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPago.setText("1");

        txtProveedor.setEditable(false);
        txtProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProveedorActionPerformed(evt);
            }
        });

        txtProducto.setEditable(false);
        txtProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtStock.setEditable(false);
        txtStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnBuscarProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarProveedor.setText("BUSCAR");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });

        btnBuscarProducto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarProducto.setText("BUSCAR");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscarPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarPago.setText("BUSCAR");
        btnBuscarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPagoActionPerformed(evt);
            }
        });

        txtMedioPago.setEditable(false);
        txtMedioPago.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMedioPago.setText("Efectivo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodProducto)
                                    .addComponent(txtPrecio)
                                    .addComponent(txtCantidad)
                                    .addComponent(txtPago, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(69, 69, 69)
                                .addComponent(txtCodProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMedioPago)
                            .addComponent(txtProducto)
                            .addComponent(txtStock)
                            .addComponent(txtProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(txtCodProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProveedor))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarProducto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarPago))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cboComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(308, 308, 308)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(53, 53, 53)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TablaDetalle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRO", "COD", "PRODUCTO", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(TablaDetalle);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGenerarCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGenerarCompra.setText("ACEPTAR");
        btnGenerarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCompraActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("TOTAL   $");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        txtTotal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTotalPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(btnGenerarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGenerarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCompraActionPerformed
       if(txtProveedor.getText().equals(""))
       {
           txtCodProveedor.requestFocus();
           txtCodProveedor.setBackground(Color.yellow);
           
           JOptionPane.showMessageDialog(this, "DEBE INGRESAR UN PROVEEDOR VALIDO");
       }
       else
       {
           int r = showConfirmDialog(null, "Esta seguro que desea realizar la compra?");
           
           if(r == 0)
           {
               generarSerie();
                guardarCompra();

               try {
                   guardarDetalle();
               } catch (SQLException ex) {
                   Logger.getLogger(Compra.class.getName()).log(Level.SEVERE, null, ex);
               }

                actualizarStock();

                nuevo();

                JOptionPane.showMessageDialog(this, "LA COMPRA SE REALIZO CON EXITO");

                txtCodProveedor.requestFocus();
                txtCodProveedor.setBackground(Color.yellow);

                txtMedioPago.setText("Efectivo");
                txtPago.setText("1");

                txtCantidad.setBackground(Color.white);
                txtCodProducto.setBackground(Color.white);

                btnBuscarProducto.setEnabled(false);
                txtCodProducto.setEnabled(false);
                btnAgregar.setEnabled(false);
                btnGenerarCompra.setEnabled(false);
           }
           else
           {
               
           }
           
       }
        
    }//GEN-LAST:event_btnGenerarCompraActionPerformed

    void guardarCompra()
    {
        int idp=Integer.parseInt(txtCodProveedor.getText());
        int formapago=Integer.parseInt(txtPago.getText());
        String serie = txtSerie.getText();
        double monto = tpagar;
        String comprobante = cboComprobante.getSelectedItem().toString();
        Date date = jdcFecha.getDate();
                
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);
        
        c.setIdProveedor(idp);
        c.setId_formapago(formapago);
        c.setMonto(monto);
        c.setNumeroSerie(serie);
        c.setComprobante(comprobante);
        c.setFecha(fecha);
        
        cdao.GuardarCompras(c);
    }
    
    void guardarDetalle() throws SQLException
    {
        String idc=cdao.IdCompras();
        int idco=Integer.parseInt(idc);
        for (int i = 0; i < TablaDetalle.getRowCount(); i++) {
            int idp=Integer.parseInt(TablaDetalle.getValueAt(i, 1).toString());
            int cantidad=Integer.parseInt(TablaDetalle.getValueAt(i, 3).toString());
            double precio=Double.parseDouble(TablaDetalle.getValueAt(i, 4).toString());
            
            dc.setIdCompra(idco);
            dc.setIdArticulo(idp);
            
            dc.setCantidad(cantidad);
            dc.setImporte(precio);
            
            cdao.GuardarDetalleCompras(dc);
        }
        
    }
    
    void actualizarStock()
    {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            Articulo a=new Articulo();
            idp=Integer.parseInt(TablaDetalle.getValueAt(i, 1).toString());
            int cant=Integer.parseInt(TablaDetalle.getValueAt(i, 3).toString());
            
            a=adao.listarID(idp);
            int sa=a.getStock()+cant;
            adao.actualizarStock(sa,idp);
        }
    }
    
    void agregarProducto()
    {
        double total=0;
        int item = 0;
        modelo=(DefaultTableModel)TablaDetalle.getModel();
        item=item+1;
        idp=Integer.parseInt(txtCodProducto.getText());
        String nomp=txtProducto.getText();
        double precio=Double.parseDouble(txtPrecio.getText());
        int cantidad=Integer.parseInt(txtCantidad.getText());
        int stock=Integer.parseInt(txtStock.getText());
        
        total=cantidad*precio;
        
        ArrayList lista = new ArrayList();
        
        lista.add(item);
        lista.add(idp);
        lista.add(nomp);
        lista.add(cantidad);
        lista.add(precio);
        lista.add(total);
        Object[]ob=new Object[6];
        ob[0]=lista.get(0);
        ob[1]=lista.get(1);
        ob[2]=lista.get(2);
        ob[3]=lista.get(3);
        ob[4]=lista.get(4);
        ob[5]=lista.get(5);
            
        modelo.addRow(ob);
        TablaDetalle.setModel(modelo);
            
        calcularTotal();
        
        //final DefaultTableCellRenderer defaultTableCellRenderer = new DefaultTableCellRenderer();
        //defaultTableCellRenderer.setHorizontalTextPosition(DefaultTableCellRenderer.RIGHT);
        //TablaDetalle.getColumnModel().getColumn(4).setCellRenderer(defaultTableCellRenderer);
        
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
        TablaDetalle.getColumnModel().getColumn(4).setCellRenderer(tcr);
        TablaDetalle.getColumnModel().getColumn(5).setCellRenderer(tcr);
        
            
            
    }
    
    void calcularTotal()
    {
        tpagar=0;
        for (int i = 0; i < TablaDetalle.getRowCount(); i++) {
            int cantidad=Integer.parseInt(TablaDetalle.getValueAt(i, 3).toString());
            double precio=Double.parseDouble(TablaDetalle.getValueAt(i, 4).toString());
            
            tpagar=tpagar+(cantidad*precio);
        }
        
        txtTotal.setText(""+tpagar);
    }
    
    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtTotalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTotalPropertyChange
        txtTotal.setHorizontalAlignment(4);
    }//GEN-LAST:event_txtTotalPropertyChange

    private void btnBuscarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPagoActionPerformed
        ListadoFormaPago la = new ListadoFormaPago();
        Principal.VentanaPrincipal.add(la);
        la.toFront();
        la.setVisible(true);

        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = la.getSize();
        la.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        la.show();
    }//GEN-LAST:event_btnBuscarPagoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(txtProducto.getText().equals(""))
        {
            txtCodProducto.requestFocus();
            txtCodProducto.setBackground(Color.yellow);
            
            txtCantidad.setBackground(Color.white);

            JOptionPane.showMessageDialog(this, "NO INGRESO UN PRODUCTO VALIDO");
        }
        else
        {
            if(txtCantidad.getText().equals(""))
            {
                txtCantidad.requestFocus();
                txtCantidad.setBackground(Color.yellow);
                
                txtCodProducto.setBackground(Color.white);

                JOptionPane.showMessageDialog(this, "NO INGRESO UNA CANTIDAD");
            }
            else
            {
                agregarProducto();

                txtCodProducto.setText("");
                txtPrecio.setText("");
                txtCantidad.setText("");
                txtProducto.setText("");
                txtStock.setText("");

                txtCodProducto.requestFocus();
                txtCodProducto.setBackground(Color.yellow);
                txtCantidad.setBackground(Color.white);

                btnGenerarCompra.setEnabled(true);

                btnAgregar.setEnabled(false);
                btnBuscarProducto.setEnabled(true);
                txtCantidad.setEnabled(false);
                txtCodProducto.setEnabled(true);
            }

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        ListadoArticulos la = new ListadoArticulos();
        Principal.VentanaPrincipal.add(la);
        la.toFront();
        la.setVisible(true);

        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = la.getSize();
        la.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        la.show();

        txtCantidad.requestFocus();
        txtCantidad.setBackground(Color.yellow);
        txtCodProducto.setBackground(Color.white);
        txtCantidad.setEnabled(true);
        btnAgregar.setEnabled(true);
        //btnBuscarProducto.setEnabled(true);
        //txtCodProducto.setEnabled(true);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
        ListadoProveedor la = new ListadoProveedor();
        Principal.VentanaPrincipal.add(la);
        la.toFront();
        la.setVisible(true);

        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = la.getSize();
        la.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        la.show();

        txtCodProducto.requestFocus();
        txtCodProducto.setBackground(Color.yellow);
        txtCodProveedor.setBackground(Color.white);
        btnBuscarProducto.setEnabled(true);
        txtCodProducto.setEnabled(true);
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void txtProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProveedorActionPerformed

    private void txtPrecioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPrecioPropertyChange
        txtPrecio.setHorizontalAlignment(4);
    }//GEN-LAST:event_txtPrecioPropertyChange

    private void txtCodProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProductoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if(txtCodProducto.getText().equals(""))
            {
                txtCodProducto.requestFocus();
                txtCodProducto.setBackground(Color.yellow);

                JOptionPane.showMessageDialog(this, "PRODUCTO NO REGISTRADO");
            }
            else
            {
                buscarProducto();
                txtCantidad.requestFocus();
                txtCantidad.setBackground(Color.yellow);
                txtCodProducto.setBackground(Color.white);

                txtCantidad.setEnabled(true);
                btnAgregar.setEnabled(true);
            }

        }
    }//GEN-LAST:event_txtCodProductoKeyPressed

    private void txtCodProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProductoActionPerformed

    private void txtCodProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodProveedorKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if(txtCodProveedor.getText().equals(""))
            {
                txtCodProveedor.requestFocus();
                txtCodProveedor.setBackground(Color.yellow);

                JOptionPane.showMessageDialog(this, "PROVEEDOR NO REGISTRADO");
            }
            else
            {
                buscarProveedor();
                txtCodProducto.setEnabled(true);
                txtCodProducto.requestFocus();
                txtCodProducto.setBackground(Color.yellow);
                btnBuscarProducto.setEnabled(true);
            }
        }
    }//GEN-LAST:event_txtCodProveedorKeyPressed

    void buscarProveedor()
    {
        int id= Integer.parseInt(txtCodProveedor.getText());
        Proveedor p = pdao.listarID(id);
        txtProveedor.setText(p.getNombre());
    }
    
    void buscarProducto()
    {
        int codigo=Integer.parseInt(txtCodProducto.getText());
        Articulo a = adao.listarID(codigo);
        
        txtProducto.setText(a.getNombre());
        txtPrecio.setText(""+a.getPrecioVenta());
        txtStock.setText(""+a.getStock());
        
        
    }
    
    void limpiarTabla()
    {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i=i-1;
        }
    }
    
    void nuevo()
    {
        limpiarTabla();
        txtCodProveedor.setText("");
        txtCodProducto.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        //txtPago.setText("");
        txtProveedor.setText("");
        txtProducto.setText("");
        txtStock.setText("");
        txtTotal.setText("");
        
        txtCodProveedor.requestFocus();;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaDetalle;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarPago;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnGenerarCompra;
    private javax.swing.JComboBox cboComprobante;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCodProducto;
    public static javax.swing.JTextField txtCodProveedor;
    public static javax.swing.JTextField txtMedioPago;
    public static javax.swing.JTextField txtPago;
    public static javax.swing.JTextField txtPrecio;
    public static javax.swing.JTextField txtProducto;
    public static javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtSerie;
    public static javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
