
package Vista;

import Gestor.Conexion;
import static Vista.ListadoCliente1.lstCliente;
import static Vista.Principal.VentanaPrincipal;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import javax.swing.table.DefaultTableModel;


public class ListadoClienteCopia extends javax.swing.JInternalFrame {

    Conexion enlace = new Conexion();
    java.sql.Connection conect = enlace.conectar();
    
    public ListadoClienteCopia() {
        initComponents();
        
        mostrarDatosCliente(0, null);
    }
    
    public void mostrarDatosCliente(int opbuscar, String valor)
    {
        DefaultTableModel tCliente = new DefaultTableModel();
        
        tCliente.addColumn("IDENTIFICACION");
        tCliente.addColumn("NOMBRE");
        
        tCliente.addColumn("RAZON SOCIAL");
        tCliente.addColumn("CODIGO POSTAL");
        tCliente.addColumn("CUIL/CUIT");
        tCliente.addColumn("DIRECCION");
        tCliente.addColumn("TELEFONO");
        
        lstCliente.setModel(tCliente);
        
        String codsql;
        
        if(opbuscar == 0 && valor == null)
        {
            codsql = "SELECT id, nombre, id_razon_social, cp, cuil, direccion, telefono FROM clientes where estado=1";
        }
        else
        {
            if(opbuscar == 1 && valor != null)
            {
                codsql = "SELECT id, nombre, id_razon_social, cp, cuil, direccion, telefono FROM clientes WHERE nombre LIKE '%"+valor+"%' and estado=1";
            }
            else
            {
                codsql = "SELECT id, nombre,id_razon_social, cp, cuil, direccion, telefono FROM clientes where estado=1";
            }
        }
        
        String []datos = new String[10];
        
        try
        {
            Statement leer = conect.createStatement();
            ResultSet resultado = leer.executeQuery(codsql);
                
            while(resultado.next())
            {
                datos[0] = resultado.getString(1);
                datos[1] = resultado.getString(2);
                datos[2] = resultado.getString(3);
                datos[3] = resultado.getString(4);
                datos[4] = resultado.getString(5);
                datos[5] = resultado.getString(6);
                datos[6] = resultado.getString(7);
                    
                tCliente.addRow(datos);
            }
            
            lstCliente.setModel(tCliente);
            
            
            
        }
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(null, e +  "Error en la consulta");
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboBuscar = new javax.swing.JComboBox<>();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCliente = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Listado Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar por:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        cboBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOSTRAR TODOS", "NOMBRE" }));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 615, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        lstCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lstCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICACION", "NOMBRE", "RAZON SOCIAL", "CODIGO POSTAL", "CUIL/CUIT", "DIRECCION", "TELEFONO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lstCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lstClienteKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(lstCliente);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("MODIFICAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("REFRESCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("ELIMINAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int opcion = cboBuscar.getSelectedIndex();
        String valorbus = txtBuscar.getText();

        mostrarDatosCliente(opcion, valorbus);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void lstClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lstClienteKeyPressed
        if(lstCliente.getSelectedRow()>=0)
        {
            try
            {
                DefaultTableModel tm = (DefaultTableModel)lstCliente.getModel();
                int id = Integer.parseInt(String.valueOf(tm.getValueAt(lstCliente.getSelectedRow(), 0)));
                String nombre = tm.getValueAt(lstCliente.getSelectedRow(),1).toString();
                SaldoCliente.txtCodCliente.setText(String.valueOf(id));
                SaldoCliente.txtCliente.setText(nombre);

                dispose();

            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "NO CONTIENE UN CLIENTE");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN CLIENTE");
        }
    }//GEN-LAST:event_lstClienteKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        RegistrarCliente lrs= new RegistrarCliente();
        Principal.VentanaPrincipal.add(lrs);
        lrs.toFront();
        lrs.setVisible(true);

        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = lrs.getSize();
        lrs.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        lrs.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(lstCliente.getSelectedRow()>=0)
        {
            try
            {

                ModificarCliente lrs= new ModificarCliente();
                Principal.VentanaPrincipal.add(lrs);
                lrs.toFront();
                lrs.setVisible(true);

                Dimension desktopSize = VentanaPrincipal.getSize();
                Dimension FrameSize = lrs.getSize();
                lrs.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
                lrs.show();

                DefaultTableModel tm = (DefaultTableModel)lstCliente.getModel();
                int id = Integer.parseInt(String.valueOf(tm.getValueAt(lstCliente.getSelectedRow(), 0)));
                String nombre = tm.getValueAt(lstCliente.getSelectedRow(),1).toString();
                int id_razon_social = Integer.parseInt(String.valueOf(tm.getValueAt(lstCliente.getSelectedRow(), 2)));
                int cp = Integer.parseInt(String.valueOf(tm.getValueAt(lstCliente.getSelectedRow(), 3)));
                int cuil = Integer.parseInt(String.valueOf(tm.getValueAt(lstCliente.getSelectedRow(), 4)));
                String direccion = tm.getValueAt(lstCliente.getSelectedRow(),5).toString();
                String telefono = tm.getValueAt(lstCliente.getSelectedRow(),6).toString();

                ModificarCliente.txtId.setText(String.valueOf(id));
                ModificarCliente.txtNombre.setText(nombre);
                ModificarCliente.txtRazon.setText(String.valueOf(id_razon_social));
                ModificarCliente.txtCp.setText(String.valueOf(cp));
                ModificarCliente.txtCuil.setText(String.valueOf(cuil));
                ModificarCliente.txtDireccion.setText(String.valueOf(direccion));
                ModificarCliente.txtTelefono.setText(String.valueOf(telefono));

                //dispose();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "NO CONTIENE UN CLIENTE");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR UN CLIENTE");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        mostrarDatosCliente(0, null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int r = showConfirmDialog(null, "ESTA SEGURO QUE DESEA ELIMINAR EL REGISTRO?");
        if(r==0)
        {
        eliminarCliente();
        }
        else
        {
        
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void eliminarCliente()
    {
        int fila = lstCliente.getSelectedRow();
        
        if(fila>=0)
        {
            try 
            {
                String valor = lstCliente.getValueAt(fila, 0).toString();
                PreparedStatement eliminar = conect.prepareStatement("UPDATE clientes set estado=2 WHERE id='"+valor+"'");
                eliminar.executeUpdate();
                mostrarDatosCliente(0,null);
            } 
            catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null,e + "No se pudo eliminar");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No selecciono ninguno");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cboBuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable lstCliente;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
