
package Vista;

import Gestor.Conexion;
//import static Vista.ListadoCliente.txtRazon;
import static Vista.Principal.VentanaPrincipal;
import static Vista.RegistrarCliente.txtRazon;
import static Vista.RegistrarCliente.validarNumeros;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;


public class ModificarCliente extends javax.swing.JInternalFrame {

    Conexion enlace = new Conexion();
    java.sql.Connection conect = enlace.conectar();
    
    public ModificarCliente() {
        initComponents();
        
        txtNombre.requestFocus();
        txtNombre.setBackground(Color.yellow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCp = new javax.swing.JTextField();
        txtCuil = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRazon = new javax.swing.JTextField();
        btnBuscarRazonSocial = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("ModificarCliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("IDENTIFICACION");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("RAZON SOCIAL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CODIGO POSTAL");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("CUIL/CUIT");

        txtCp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpKeyPressed(evt);
            }
        });

        txtCuil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCuil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCuilKeyPressed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("DIREECION");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("TELEFONO");

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
        });

        txtRazon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRazon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRazonKeyPressed(evt);
            }
        });

        btnBuscarRazonSocial.setText("...");
        btnBuscarRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRazonSocialActionPerformed(evt);
            }
        });

        jLabel8.setText("* Campos requeridos");

        jLabel10.setText("*");

        jLabel9.setText("*");

        jLabel11.setText("*");

        jLabel15.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCp, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                                    .addComponent(txtCuil)
                                    .addComponent(txtNombre)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtRazon))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 28, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRazonSocial)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("CANCELAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregar.setText("ACEPTAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtCuil.requestFocus();
            txtCuil.setBackground(Color.YELLOW);
            txtCp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtCpKeyPressed

    private void txtCuilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuilKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtDireccion.requestFocus();
            txtDireccion.setBackground(Color.YELLOW);
            txtCuil.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtCuilKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtRazon.requestFocus();
            txtRazon.setBackground(Color.YELLOW);
            txtNombre.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtTelefono.requestFocus();
            txtTelefono.setBackground(Color.YELLOW);
            txtDireccion.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            btnAgregar.requestFocus();
            btnAgregar.setBackground(Color.YELLOW);
            txtDireccion.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtRazonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtCp.requestFocus();
            txtCp.setBackground(Color.YELLOW);
            txtRazon.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtRazonKeyPressed

    private void btnBuscarRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRazonSocialActionPerformed
        ListadoRazonSocialCopiaCopia lrs= new ListadoRazonSocialCopiaCopia();
        Principal.VentanaPrincipal.add(lrs);
        lrs.toFront();
        lrs.setVisible(true);

        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = lrs.getSize();
        lrs.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        lrs.show();
    }//GEN-LAST:event_btnBuscarRazonSocialActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        int r = showConfirmDialog(null, "DESEA MODIFICAR EL CLIENTE?");
        if(r == 0){
        agregar();
        }
        else{}
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    void agregar()
    {
        if(txtNombre.getText().equals(""))
        {
            txtNombre.requestFocus();
            txtNombre.setBackground(Color.yellow);
            
            txtCp.setBackground(Color.white);
            txtCuil.setBackground(Color.white);
            txtDireccion.setBackground(Color.white);
            txtTelefono.setBackground(Color.white);
            
            JOptionPane.showMessageDialog(this, "Debe ingresar un NOMBRE");
        }
        else
        {
            if(txtCp.getText().equals(""))
            {
                txtCp.requestFocus();
                txtCp.setBackground(Color.yellow);
                
                txtNombre.setBackground(Color.white);
                txtCuil.setBackground(Color.white);
                txtDireccion.setBackground(Color.white);
                txtTelefono.setBackground(Color.white);
                
                JOptionPane.showMessageDialog(this, "Debe ingresar un CODIGO POSTAL");
            }
            else
            {
                if(txtCuil.getText().equals(""))
                {
                    txtCuil.requestFocus();
                    txtCuil.setBackground(Color.yellow);
                    
                    txtNombre.setBackground(Color.white);
                    txtCp.setBackground(Color.white);
                    txtDireccion.setBackground(Color.white);
                    txtTelefono.setBackground(Color.white);
                    
                    JOptionPane.showMessageDialog(this, "Debe ingresar un CUIL/CUIT");
                }
                else
                {
                    if(!validarNumeros(txtCp.getText().trim()))
                            {
                                txtCp.requestFocus();
                                txtCp.setBackground(Color.yellow);
                                
                                txtRazon.setBackground(Color.white);
                                txtTelefono.setBackground(Color.white);
                                txtCuil.setBackground(Color.white);
                                txtDireccion.setBackground(Color.white);
                                txtNombre.setBackground(Color.white);
                                
                                JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo CODIGO POSTAL");
                            }
                            else
                            {
                                if(!validarNumeros(txtCuil.getText().trim()))
                                {
                                    txtCuil.requestFocus();
                                    txtCuil.setBackground(Color.yellow);
                                    
                                    txtRazon.setBackground(Color.white);
                                    txtTelefono.setBackground(Color.white);
                                    txtCp.setBackground(Color.white);
                                    txtDireccion.setBackground(Color.white);
                                    txtNombre.setBackground(Color.white);

                                    JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo CUIL/CUIT");
                                }
                                else
                                {
                                    if(!validarNumeros(txtTelefono.getText().trim()))
                                    {
                                        txtTelefono.requestFocus();
                                        txtTelefono.setBackground(Color.yellow);
                                        
                                        txtRazon.setBackground(Color.white);
                                        txtCuil.setBackground(Color.white);
                                        txtCp.setBackground(Color.white);
                                        txtDireccion.setBackground(Color.white);
                                        txtNombre.setBackground(Color.white);
                                        
                                        JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo TELEFONO");
                                    }
                                    else
                                    {
                                        actualizarCliente();
                                        
                                        dispose();
                            
                                        txtNombre.requestFocus();
                                        txtNombre.setBackground(Color.yellow);

                                        txtCp.setBackground(Color.white);
                                        txtCuil.setBackground(Color.white);
                                        txtDireccion.setBackground(Color.white);
                                        txtTelefono.setBackground(Color.white);
                                        txtRazon.setBackground(Color.white);

                                        //JOptionPane.showMessageDialog(this, "CLIENTE CARGADO EXITOSAMENTE");
                                    }
                                }
                            }
                }
            }
        }
        
    }
    
    void actualizarCliente()
    {
        try {
            PreparedStatement pst = conect.prepareStatement("UPDATE clientes SET nombre='"+txtNombre.getText()+"',id_razon_social='"+txtRazon.getText()+"',cp='"+txtCp.getText()+"',cuil='"+txtCuil.getText()+"',direccion='"+txtDireccion.getText()+"',telefono='"+txtTelefono.getText()+"' WHERE id='"+txtId.getText()+"'");
            pst.executeUpdate();
            //mostrarDatosCliente(0, null);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    public static boolean validarNumeros(String datos)
    {
        return datos.matches("[0-9-.]*");
        //return datos.marches("[0-9]{1, 3}"); PARA LA CANTIDAD DE DIGITOS POSIBLES
        //return datos.marches("[a-zA-Z]*");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarRazonSocial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtCp;
    public static javax.swing.JTextField txtCuil;
    public static javax.swing.JTextField txtDireccion;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtRazon;
    public static javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
