
package Vista;

import Gestor.Conexion;
import Gestor.GestorDB;
import Modelo.Cliente;
import Modelo.RazonSocial;
//import static Vista.ListadoCliente.validarNumeros;
import static Vista.Principal.VentanaPrincipal;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;


public class RegistrarCliente extends javax.swing.JInternalFrame {

    
    private GestorDB g;

    Conexion enlace = new Conexion();
    java.sql.Connection conect = enlace.conectar();
    
    
    public RegistrarCliente() {
        initComponents();
        
        g = new GestorDB();
        
        cargarRazonSocial();
        
        txtNombre.requestFocus();
        txtNombre.setBackground(Color.yellow);
    }
    
    private void cargarRazonSocial()
    {
        ArrayList<RazonSocial> razonsocial = g.obtenerRazonSocial();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCp = new javax.swing.JTextField();
        txtCuil = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRazon = new javax.swing.JTextField();
        btnBuscarRazonSocial = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jLabel12.setText("*");

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("IDENTIFICACION");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("NOMBRE");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("RAZON SOCIAL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CODIGO POSTAL");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("CUIL/CUIT");

        txtCp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCpKeyPressed(evt);
            }
        });

        txtCuil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCuil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCuilKeyPressed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("DIREECION");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("TELEFONO");

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
        });

        txtRazon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRazon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRazonKeyPressed(evt);
            }
        });

        btnBuscarRazonSocial.setText("...");
        btnBuscarRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRazonSocialActionPerformed(evt);
            }
        });

        jLabel8.setText("* Campos requeridos");

        jLabel10.setText("*");

        jLabel9.setText("*");

        jLabel11.setText("*");

        jLabel15.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCp, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                                    .addComponent(txtCuil)
                                    .addComponent(txtNombre)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtRazon))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRazonSocial)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCuil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        btnAgregar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAgregar.setText("ACEPTAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel13.setText("*");

        jLabel14.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 260, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(438, 438, 438)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(438, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(438, 438, 438)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(438, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(273, 273, 273)
                    .addComponent(jLabel13)
                    .addContainerGap(274, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(273, 273, 273)
                    .addComponent(jLabel14)
                    .addContainerGap(274, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void agregar()
    {
        if(txtNombre.getText().equals(""))
        {
            txtNombre.requestFocus();
            txtNombre.setBackground(Color.yellow);
            
            txtCp.setBackground(Color.white);
            txtCuil.setBackground(Color.white);
            txtDireccion.setBackground(Color.white);
            txtTelefono.setBackground(Color.white);
            
            JOptionPane.showMessageDialog(this, "Debe ingresar un NOMBRE");
        }
        else
        {
            if(txtCp.getText().equals(""))
            {
                txtCp.requestFocus();
                txtCp.setBackground(Color.yellow);
                
                txtNombre.setBackground(Color.white);
                txtCuil.setBackground(Color.white);
                txtDireccion.setBackground(Color.white);
                txtTelefono.setBackground(Color.white);
                
                JOptionPane.showMessageDialog(this, "Debe ingresar un CODIGO POSTAL");
            }
            else
            {
                if(txtCuil.getText().equals(""))
                {
                    txtCuil.requestFocus();
                    txtCuil.setBackground(Color.yellow);
                    
                    txtNombre.setBackground(Color.white);
                    txtCp.setBackground(Color.white);
                    txtDireccion.setBackground(Color.white);
                    txtTelefono.setBackground(Color.white);
                    
                    JOptionPane.showMessageDialog(this, "Debe ingresar un CUIL/CUIT");
                }
                else
                {
                    if(!validarNumeros(txtCp.getText().trim()))
                            {
                                txtCp.requestFocus();
                                txtCp.setBackground(Color.yellow);
                                
                                txtRazon.setBackground(Color.white);
                                txtTelefono.setBackground(Color.white);
                                txtCuil.setBackground(Color.white);
                                txtDireccion.setBackground(Color.white);
                                txtNombre.setBackground(Color.white);
                                
                                JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo CODIGO POSTAL");
                            }
                            else
                            {
                                if(!validarNumeros(txtCuil.getText().trim()))
                                {
                                    txtCuil.requestFocus();
                                    txtCuil.setBackground(Color.yellow);
                                    
                                    txtRazon.setBackground(Color.white);
                                    txtTelefono.setBackground(Color.white);
                                    txtCp.setBackground(Color.white);
                                    txtDireccion.setBackground(Color.white);
                                    txtNombre.setBackground(Color.white);

                                    JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo CUIL/CUIT");
                                }
                                else
                                {
                                    if(!validarNumeros(txtTelefono.getText().trim()))
                                    {
                                        txtTelefono.requestFocus();
                                        txtTelefono.setBackground(Color.yellow);
                                        
                                        txtRazon.setBackground(Color.white);
                                        txtCuil.setBackground(Color.white);
                                        txtCp.setBackground(Color.white);
                                        txtDireccion.setBackground(Color.white);
                                        txtNombre.setBackground(Color.white);
                                        
                                        JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo TELEFONO");
                                    }
                                    else
                                    {
                                        agregarCliente();
                            
                                        txtNombre.requestFocus();
                                        txtNombre.setBackground(Color.yellow);

                                        txtCp.setBackground(Color.white);
                                        txtCuil.setBackground(Color.white);
                                        txtDireccion.setBackground(Color.white);
                                        txtTelefono.setBackground(Color.white);
                                        txtRazon.setBackground(Color.white);

                                        JOptionPane.showMessageDialog(this, "CLIENTE CARGADO EXITOSAMENTE");
                                    }
                                }
                            }
                }
            }
        }
        
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int r = showConfirmDialog(null, "DESEA REGISTRAR EL CLIENTE?");
        
        if(r==0)
        {
            agregar();
        }
        else
        {
            
        }
        
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    public static boolean validarNumeros(String datos)
    {
        return datos.matches("[0-9]*");
        //return datos.marches("[0-9]{1, 3}"); PARA LA CANTIDAD DE DIGITOS POSIBLES
        //return datos.marches("[a-zA-Z]*");
    }
    
    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtRazon.requestFocus();
            txtRazon.setBackground(Color.YELLOW);
            txtNombre.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtCuil.requestFocus();
            txtCuil.setBackground(Color.YELLOW);
            txtCp.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtCpKeyPressed

    private void txtCuilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuilKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtDireccion.requestFocus();
            txtDireccion.setBackground(Color.YELLOW);
            txtCuil.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtCuilKeyPressed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtTelefono.requestFocus();
            txtTelefono.setBackground(Color.YELLOW);
            txtDireccion.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            btnAgregar.requestFocus();
            btnAgregar.setBackground(Color.YELLOW);
            txtDireccion.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtRazonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtCp.requestFocus();
            txtCp.setBackground(Color.YELLOW);
            txtRazon.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtRazonKeyPressed

    private void btnBuscarRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRazonSocialActionPerformed
        ListadoRazonSocialCopiaCopia lrs= new ListadoRazonSocialCopiaCopia();
        Principal.VentanaPrincipal.add(lrs);
        lrs.toFront();
        lrs.setVisible(true);
        
        Dimension desktopSize = VentanaPrincipal.getSize();
        Dimension FrameSize = lrs.getSize();
        lrs.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        lrs.show();
    }//GEN-LAST:event_btnBuscarRazonSocialActionPerformed

    
    void agregarCliente()
    {
        try
        {
            PreparedStatement guardar = conect.prepareStatement("INSERT INTO clientes (nombre, id_razon_social, cp,cuil, direccion, telefono, estado) VALUES (?, ?, ?, ?, ?,?, 1)");
            guardar.setString(1, txtNombre.getText());
            guardar.setString(2, txtRazon.getText());
            guardar.setString(3, txtCp.getText());
            guardar.setString(4, txtCuil.getText());
            guardar.setString(5, txtDireccion.getText());
            guardar.setString(6, txtTelefono.getText());
            
            guardar.executeUpdate();
            
            //JOptionPane.showMessageDialog(null, "Cliente cargado exitosamente");
            
            txtNombre.setText("");
            txtCp.setText("");
            txtCuil.setText("");
            txtDireccion.setText("");
            txtTelefono.setText("");
            txtRazon.setText("");
            txtNombre.requestFocus();
            
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e + "No se pudo cargar");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarRazonSocial;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCp;
    private javax.swing.JTextField txtCuil;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtRazon;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
