
package Vista;

import Gestor.Conexion;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


public class RegistrarArticulo extends javax.swing.JInternalFrame {

    Conexion enlace = new Conexion();
    java.sql.Connection conect = enlace.conectar();
    
    
    public RegistrarArticulo() {
        initComponents();
        
        txtNombre.setBackground(Color.YELLOW);
        txtNombre.requestFocus();
    }
    
    void agregarArticulo()
    {
        try 
        {
            PreparedStatement guardar = conect.prepareStatement("INSERT INTO articulos (nombre, precioCompra, precioVenta,stock, stockMinimo, estado) VALUES (?, ?, ?, ?, ?, 1)");
            guardar.setString(1, txtNombre.getText());
            guardar.setString(2, txtCompra.getText());
            guardar.setString(3, txtVenta.getText());
            guardar.setString(4, txtStock.getText());
            guardar.setString(5, txtStockMinimo.getText());
            
            guardar.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "ARTICULO CARGADO EXITOSAMENTE");
            
            txtNombre.setText("");
            txtVenta.setText("");
            txtCompra.setText("");
            txtStock.setText("");
            txtStockMinimo.setText("");
            txtNombre.requestFocus();
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, e + "NO SE PUDO CARGAR EL ARTICULO");
        }
        
        txtStockMinimo.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCompra = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtStockMinimo = new javax.swing.JTextField();
        txtVenta = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Articulo");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("NOMBRE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("PRECIO VENTA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("PRECIO COMPRA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("STOCK");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("STOCK MINIMO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("CODIGO");

        txtCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCompraKeyPressed(evt);
            }
        });

        txtStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStockKeyPressed(evt);
            }
        });

        txtStockMinimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVentaKeyPressed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setText("* Campos requeridos");

        jLabel9.setText("*");

        jLabel10.setText("*");

        jLabel11.setText("*");

        jLabel12.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtStock)
                            .addComponent(txtCompra)
                            .addComponent(txtStockMinimo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre)
                            .addComponent(txtVenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(txtVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStockMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
   
        if(txtNombre.getText().equals("") )
        {
            txtNombre.requestFocus();
            txtNombre.setBackground(Color.yellow);
            txtVenta.setBackground(Color.white);
            txtCompra.setBackground(Color.white);
            txtStock.setBackground(Color.white);
            txtStockMinimo.setBackground(Color.white);
            
            JOptionPane.showMessageDialog(this, "Debe ingresar nombre del producto");
        }
        else
        {
            if(txtVenta.getText().equals(""))
            {
                txtVenta.requestFocus();
                txtVenta.setBackground(Color.yellow);
                txtNombre.setBackground(Color.white);
                txtCompra.setBackground(Color.white);
                txtStock.setBackground(Color.white);
                txtStockMinimo.setBackground(Color.white);
                
                JOptionPane.showMessageDialog(this, "Debe ingresar el precio de venta");
            }
            else
            {
                if(txtCompra.getText().equals(""))
                {
                    txtCompra.requestFocus();
                    txtCompra.setBackground(Color.yellow);
                    txtNombre.setBackground(Color.white);
                    txtVenta.setBackground(Color.white);
                    txtStock.setBackground(Color.white);
                    txtStockMinimo.setBackground(Color.white);
                    
                    JOptionPane.showMessageDialog(this, "Debe ingresar el precio de compra");
                }
                else
                {
                    
                    
                    
                        if(txtStockMinimo.getText().equals(""))
                        {
                            txtStockMinimo.requestFocus();
                            txtStockMinimo.setBackground(Color.yellow);
                            txtStock.setBackground(Color.white);
                            txtCompra.setBackground(Color.white);
                            txtNombre.setBackground(Color.white);
                            txtVenta.setBackground(Color.white);
                            
                            JOptionPane.showMessageDialog(this, "Debe ingresar el stock minimo");
                        }
                        else
                        {
                            if(!validarNumeros(txtVenta.getText().trim()))
                            {
                                txtVenta.requestFocus();
                                txtVenta.setBackground(Color.yellow);
                                txtNombre.setBackground(Color.white);
                                txtCompra.setBackground(Color.white);
                                txtStock.setBackground(Color.white);
                                txtStockMinimo.setBackground(Color.white);
                                
                                JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo PRECIO VENTA");
                            }
                            else
                            {
                                if(!validarNumeros(txtCompra.getText().trim()))
                                {
                                    txtCompra.requestFocus();
                                    txtCompra.setBackground(Color.yellow);
                                    txtNombre.setBackground(Color.white);
                                    txtVenta.setBackground(Color.white);
                                    txtStock.setBackground(Color.white);
                                    txtStockMinimo.setBackground(Color.white);
                                    
                                    JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo PRECIO COMPRA");
                                }
                                else
                                {
                                    if(!validarNumeros(txtStock.getText().trim()))
                                    {
                                        txtStock.requestFocus();
                                        txtStock.setBackground(Color.yellow);
                                        txtCompra.setBackground(Color.white);
                                        txtNombre.setBackground(Color.white);
                                        txtVenta.setBackground(Color.white);
                                        txtStockMinimo.setBackground(Color.white);
                                        
                                        JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo STOCK");
                                    }
                                    else
                                    {
                                        if(!validarNumeros(txtStockMinimo.getText().trim()))
                                        {
                                            txtStockMinimo.requestFocus();
                                            txtStockMinimo.setBackground(Color.yellow);
                                            txtStock.setBackground(Color.white);
                                            txtCompra.setBackground(Color.white);
                                            txtNombre.setBackground(Color.white);
                                            txtVenta.setBackground(Color.white);
                                            
                                            JOptionPane.showMessageDialog(null, "Debe ingresar solo numeros en el campo STOCK MINIMO");
                                        }
                                        else
                                        {
                                            int r = JOptionPane.showConfirmDialog(null, "DESEA REGISTRAR EL ARTICULO?");
                                            
                                            if(r==0)
                                            {
                                                agregarArticulo();
                            
                                                txtStockMinimo.setBackground(Color.white);
                                                txtStock.setBackground(Color.white);
                                                txtCompra.setBackground(Color.white);
                                                txtNombre.setBackground(Color.yellow);
                                                txtVenta.setBackground(Color.white);
                                                txtNombre.requestFocus();
                                            }
                                            else
                                            {
                                                
                                            }
                                            
                                            
                                        }
                                    }
                                }
                            }
                            
                            
                            
                        }
                    
                }
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtVenta.requestFocus();
            txtVenta.setBackground(Color.YELLOW);
            txtNombre.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVentaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtCompra.requestFocus();
            txtCompra.setBackground(Color.YELLOW);
            txtVenta.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtVentaKeyPressed

    private void txtCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompraKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtStock.requestFocus();
            txtStock.setBackground(Color.YELLOW);
            txtCompra.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtCompraKeyPressed

    private void txtStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            txtStockMinimo.requestFocus();
            txtStockMinimo.setBackground(Color.YELLOW);
            txtStock.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_txtStockKeyPressed

    
    public static boolean validarNumeros(String datos)
    {
        return datos.matches("[0-9-.]*");
        //return datos.marches("[0-9]{1, 3}"); PARA LA CANTIDAD DE DIGITOS POSIBLES
        //return datos.marches("[a-zA-Z]*");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtCompra;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtStockMinimo;
    private javax.swing.JTextField txtVenta;
    // End of variables declaration//GEN-END:variables
}
